if: branch = master
language: scala
scala:
- 2.12.6
script: sbt test
after_success:
- "./release.sh"
notifications:
  slack:
    secure: n/kBiu7Ykws/NvbQh/4fhQ3D7rBv2MvjTCN52HZWeexqjCgfcqREJc+2uGvDImfaR59p4/AIyFqU0+mJU3io7SHPlmFg9Lck3hwDEvYypOopvGX0pPySdyJG5X7O0mh8pTRIWj0vPDBWr9eA6PcFs+9jM15zbKMOA+fyugjWlttz3CbB8Xu9ykdgT6moEZuTUIZWJQn02yKAnUNI1No8XA3mOM+ZcO+l4CodN0q8aJ1qUoN6FfUs+bn9T8sw+VZkOi/SmVo6EAii8VslXsGNCQ2yS3ZO2zLZwHOzKH0ap+4Msi2n2AO0f0W4Y4ZEhdP/OeGQjGy94K3dZaOW72V+8UTP8b9BV2YtVOYvDeChDrHvKks6ktZU+pzCHiQ3LR9SaSRMzs10QKx4w4k+Ti3Ag+e7RY3QDgKCLzow9JiIzSo+lBcSFFlbw9YQpQ2M8Kdnw691hFOdgQsJ4/aXc4fvC9+X8R+mVO9EGfZT5UUV+OltMmvB50t8I3FHCAbsqyivCXnQnPoiQzZ76LOFE/bvFiNckF5mDz32fWsEOmFGDe6krTX4N26SC+hYLqwLSY+PztrKxmKMD4f2hYtqq3sz3hrukGvM4b/AaFGBV7fP91odebQ5au8KdRoihD28sGuJJgUAXGfrorOyqQH1ocBFl0eHCC0lfPnM6VMekfxDdG0=
  email:
    on_success: never
    on_failure: never
